// Generated by ego on Sat Sep 26 13:45:18 2015.
// DO NOT EDIT

package main
import (
"fmt"
"html"
"io"
"strconv"
)
//line templates/query.ego:1
 func RenderQuery(w io.Writer, readings []Reading) error  {
//line templates/query.ego:2
_, _ = fmt.Fprint(w, "\n")
//line templates/query.ego:3
_, _ = fmt.Fprint(w, "\n\n<html>\n<head>\n  <style>\n    body { background-color: tan }\n    ul { list-style-type:none; margin: 0; padding: 0; }\n    ul.topmost > li:first-child { border-top: 1px solid #531C1C}\n    ul.topmost > li { border-top:none; border-bottom: 1px solid #8A2E2E; padding: 0.3em 0.3em}\n    li { border-top: 1px solid #B89c72; line-height:1.2em; padding: 1.2em, 4em }\n    .h1 { font-size: 1.2em; margin-bottom: 0.1em; padding: 0.1em }\n    .temp { font-weight: bold; }\n    .temp_fail { color:red; }\n    .temp_hot { color:#a07030; }\n    .temp_warm { color:yellow; }\n    .temp_good { color:darkgreen; }\n    .fixed-heading { position: fixed; top: 0; left: 0; width:100%; z-index:2; background-color:tan; opacity:0.95 }\n    .temp_heading td { border: 1px solid gray }\n    .temp_data { margin-top: 2.8em; }\n    .title { font-weight: bold; color:darkgreen; padding-top: 0.4em }\n    .count { font-size: 0.8em; color:#401020; padding-left: 0.5em; padding-right: 0.5em }\n    .tool { font-size: 0.7em; color:#401020; padding-left: 0.5em }\n    code { -webkit-border-radius: 0.3em;\n          -moz-border-radius: 0.3em;\n          border-radius: 0.3em; }\n  </style>\n  <script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-2.1.3.min.js\"></script>\n</head>\n<body>\n")
//line templates/query.ego:31
 readings_count := len(readings) 
//line templates/query.ego:32
_, _ = fmt.Fprint(w, "\n<div class=\"fixed-heading\">\n  <span class=\"h1\">KittyMon</span> <span class=\"count\">")
//line templates/query.ego:33
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  readings_count )))
//line templates/query.ego:33
_, _ = fmt.Fprint(w, " found</span>  <a class=\"tool\" href=\"/q/all\">All</a>\n  <table class=\"temp_heading\">\n  <tr><td>Temp</td><td>Created At</td><td>Reading Guid</td><td>Soure Guid</td><td>Source IP</td>\n      ")
//line templates/query.ego:36
 if readings_count == 1 { 
//line templates/query.ego:37
_, _ = fmt.Fprint(w, "\n        <td>Delete</td>\n      ")
//line templates/query.ego:38
 } 
//line templates/query.ego:39
_, _ = fmt.Fprint(w, "\n  </tr>\n  </table>\n</div>\n\n<table class=\"temp_data\">\n  ")
//line templates/query.ego:44
 var temp_class string 
//line templates/query.ego:45
_, _ = fmt.Fprint(w, "\n  ")
//line templates/query.ego:45
 for _, reading := range readings { 
//line templates/query.ego:46
_, _ = fmt.Fprint(w, "\n      ")
//line templates/query.ego:47

        switch {
        case reading.Temp > 64:
          temp_class = "temp_fail"
        case reading.Temp > 62:
          temp_class = "temp_hot"
        case reading.Temp > 59:
          temp_class = "temp_warm"
        default:
          temp_class = "temp_good"
        }
      
//line templates/query.ego:59
_, _ = fmt.Fprint(w, "\n      <tr>\n\n      ")
//line templates/query.ego:61
 if reading.Temp == -255 { 
//line templates/query.ego:62
_, _ = fmt.Fprint(w, "\n       <td>N/A</td>\n      ")
//line templates/query.ego:63
 } else { 
//line templates/query.ego:64
_, _ = fmt.Fprint(w, "\n       <td class=\"temp ")
//line templates/query.ego:64
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v", temp_class )))
//line templates/query.ego:64
_, _ = fmt.Fprint(w, "\">")
//line templates/query.ego:64
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  reading.Temp )))
//line templates/query.ego:64
_, _ = fmt.Fprint(w, "</td>\n      ")
//line templates/query.ego:65
 } 
//line templates/query.ego:66
_, _ = fmt.Fprint(w, "\n\n      <td>")
//line templates/query.ego:67
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  reading.CreatedAt.Format("15:04:05 Mon Jan _2") )))
//line templates/query.ego:67
_, _ = fmt.Fprint(w, "</td>\n      <td>")
//line templates/query.ego:68
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  short_sha(reading.Guid) )))
//line templates/query.ego:68
_, _ = fmt.Fprint(w, "</td>\n      <td>")
//line templates/query.ego:69
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  short_sha(reading.SourceGuid) )))
//line templates/query.ego:69
_, _ = fmt.Fprint(w, "</td>\n      <td>")
//line templates/query.ego:70
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  reading.IPs )))
//line templates/query.ego:70
_, _ = fmt.Fprint(w, "</td>\n      ")
//line templates/query.ego:71
 if readings_count == 1 { 
//line templates/query.ego:72
_, _ = fmt.Fprint(w, "\n      ")
//line templates/query.ego:72
 id_str := strconv.FormatInt(reading.Id, 10) 
//line templates/query.ego:73
_, _ = fmt.Fprint(w, "\n      <td><a class=\"tool\" href=\"/del/")
//line templates/query.ego:73
_, _ = fmt.Fprint(w, html.EscapeString(fmt.Sprintf("%v",  id_str )))
//line templates/query.ego:73
_, _ = fmt.Fprint(w, "\"\n            onclick=\"return confirm('Are you sure you want to delete this reading?')\">\n        delete</a>\n      </td>\n      ")
//line templates/query.ego:77
 } 
//line templates/query.ego:78
_, _ = fmt.Fprint(w, "\n\n      </tr>\n  ")
//line templates/query.ego:80
 } 
//line templates/query.ego:81
_, _ = fmt.Fprint(w, "\n</table>\n\n<script type=\"text/javascript\">\n  $( function() {\n    //el = $('.reading-body');\n    //el.find(\"pre code\").each( function(i, block) {\n    //  hljs.highlightBlock( block );\n    //})\n  });\n</script>\n\n</body>\n</html>\n")
return nil
}
